plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

ext {
    PUBLISH_ARTIFACT_ID = 'analytiks-appsflyer'
}
apply from: "${rootProject.projectDir}/scripts/publish-module.gradle"

android {
    namespace 'com.analytiks.addon.appsflyer'
    compileSdk rootProject.compileSdk

    defaultConfig {
        minSdk 21
        targetSdk rootProject.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    api project(':analytiks')
    implementation 'com.appsflyer:af-android-sdk:6.17.0'
}
