name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Skip the build action if only the README file is changed
    - name: Check if README is the only file changed
      run: |
        if git diff --name-only HEAD HEAD~1 | grep -q "^README.md$"; then
          echo "Only README.md is changed. Skipping build."
          exit 78 # Skip the rest of the job
        fi
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

